/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Alpaca.gltf 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { AnimationMixer, AnimationUtils } from 'three'

// export default function Model(props) {
//   const group = useRef()
//   // const { nodes, materials, animations } = useGLTF('../assets/3d/Alpaca.gltf')
//   const { nodes, materials, animations } = useGLTF('.../public/Alpaca.gltf')

//   const { actions } = useAnimations(animations, group)

const Alpaca = ({ currentAnimation, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/Alpaca.gltf');
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    console.log(actions);
    actions.Gallop.play();
    // actions.Eating.play();

    // Object.values(actions).forEach((action) => action.stop());

    // if (actions[currentAnimation]) {
    //   actions[currentAnimation].play();
    // }

  })
  // , [actions, currentAnimation])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="AnimalArmature">
          <primitive object={nodes.Body} />
          <primitive object={nodes.IKBackLegL} />
          <primitive object={nodes.IKFrontLegL} />
          <primitive object={nodes.IKBackLegR} />
          <primitive object={nodes.IKFrontLegR} />
          <group name="Alpaca">
            <skinnedMesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Main} skeleton={nodes.Cube.skeleton} />
            <skinnedMesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Main_Light} skeleton={nodes.Cube_1.skeleton} />
            <skinnedMesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials.Hooves} skeleton={nodes.Cube_2.skeleton} />
            <skinnedMesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials.Main_Dark} skeleton={nodes.Cube_3.skeleton} />
            <skinnedMesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials.Muzzle} skeleton={nodes.Cube_4.skeleton} />
            <skinnedMesh name="Cube_5" geometry={nodes.Cube_5.geometry} material={materials.Eyes_Black} skeleton={nodes.Cube_5.skeleton} />
            <skinnedMesh name="Cube_6" geometry={nodes.Cube_6.geometry} material={materials.Eyes_White} skeleton={nodes.Cube_6.skeleton} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/Alpaca.gltf')

export default Alpaca