/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-in-the-cloud-b270497defe24f9cb497b9a075eeb28f
Title: FREE - SkyBox In The Cloud
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Sky_Test = ({ props }) => {
    const { nodes, materials } = useGLTF("/sky.glb");
    return (
        <group {...props} dispose={null}>
            <group scale={0.01}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Sphere__0.geometry}
                    material={materials["Scene_-_Root"]}
                    rotation={[-Math.PI / 2, 0, 0]}
                    scale={50000}
                />
            </group>
        </group>
    );
}

useGLTF.preload("/sky.glb");

export default Sky_Test
